# Generated by Django 2.2.5 on 2021-05-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prouct_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField()),
                ('product_weight', models.FloatField()),
                ('created_at', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
            ],
        ),
    ]
